### ISSUE TITLE
y does not work in setup.py

### ISSUE THREAD

**Issue by wish13yt** [Block0S/CLBOS-Command-Line-BlockOS-#1]
In order to use Setup.py, you **Need** to type a capital Y. If you type a lowercase y, it only creates the files.

**Comment by Block0S** [comment]
You have to debug Setup.py (As well CLBOS.py when you use it) In a terminal, such as Visual Studio Code's debugger for example.

**Comment by wish13yt** [comment]
Hey! This was not what I meant.
It works fine if you type a capital Y, but it wont enter setup if you type a lowercase y.

**Comment by Block0S** [comment]
Oh, I always typed "Y" When testing it out.
Thanks for telling me, I will fix that in the next version!
